import Head from 'next/head'
import SectionCover from '@/components/SectionCover'
import SectionArticle from '@/components/SectionArticle'
import SectionVideo from '@/components/SectionVideo'
import SectionStats from '@/components/SectionStats'
import SectionAlbum from '@/components/SectionAlbum'

export default function Home() {
  return (
    <>
      <Head>
        <title>可可托海没有海</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SectionCover />
        <SectionArticle />
        <SectionAlbum />
        <SectionVideo />
        <SectionStats />
      </main>
    </>
  )
}
